# Use uma imagem base do Python
FROM python:3.10-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo requirements.txt
COPY requirements.txt .

# Instale as dependências listadas no requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante do código da aplicação para o contêiner
COPY . /app

# Exponha a porta 5002
EXPOSE 5002

# Comando para rodar o aplicativo
CMD ["python", "app.py"]
