# Use uma imagem base do Python
FROM python:3.10-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo requirements.txt (se você tiver um) ou liste as dependências diretamente
# Se você tiver um requirements.txt
COPY requirements.txt .

# Caso contrário, você pode listar as dependências aqui
RUN pip install flask

# Copie o restante do código da aplicação para o contêiner
COPY . /app

EXPOSE 3002

# Comando para rodar o aplicativo
CMD ["python", "app.py"]
