networks:
  rede_microsservicos:
    external: true

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_postgres=test_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.2

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doxito007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:8080"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.3
    depends_on:
      - postgres

  controller-cadastro-autenticacao:
    image: jonasrsribeiro/nc-controller-cadastro-autenticacao:prod
    ports:
      - "5000:5000"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.4
    depends_on:
      - pgadmin
      - postgres

  #controller-preferencia-area:
  #  image: jonasrsribeiro/nc-controller-preferencia-area:prod
  #  ports:
  #    - "3001:3001"
  #  restart: always
  #  networks:
  #    rede_microsservicos:
  #      ipv4_address: 172.18.0.5
  #  depends_on:
  #    - pgadmin
  #    - postgres
  #    - controller-cadastro-autenticacao
  
  #controller-obter-imagens:
  #  image: jonasrsribeiro/nc-controller-obter-imagens:prod
  #  ports:
  #    - "3003:3003"
  #  restart: always
  #  networks:
  #    rede_microsservicos:
  #      ipv4_address: 172.18.0.8
  #  depends_on:
  #    - pgadmin
  #    - postgres
  #    - controller-cadastro-autenticacao
  #    - controller-preferencia-area

  #controller-conversor:
  #  image: jonasrsribeiro/nc-controller-conversor:prod
  #  ports:
  #    - "3004:3004"
  #  restart: always
  #  networks:
  #    rede_microsservicos:
  #      ipv4_address: 172.18.0.9
  #  depends_on:
  #    - pgadmin
  #    - postgres
  #    - controller-cadastro-autenticacao
  #    - controller-preferencia-area
  #    - controller-obter-imagens

  controller-identificacao-ia:
    image: jonasrsribeiro/nc-controller-identificacao-ia:prod
    ports:
      - "5002:5002"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.7
    depends_on:
      - pgadmin
      - postgres
      - controller-cadastro-autenticacao

  frontend:
    image: jonasrsribeiro/nc-controller-frontend:prod
    ports:
      - "8080:8080"
    volumes:
      - front-data:/app
    environment:
      - NODE_ENV=development
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.6
    depends_on:
      - pgadmin
      - postgres
      - controller-cadastro-autenticacao
      #- controller-preferencia-area
      #- controller-obter-imagens
      #- controller-conversor
      - controller-identificacao-ia

volumes:
  postgres-data:
  front-data:
