# Use uma imagem base do Miniconda
FROM continuumio/miniconda3

# Atualize os pacotes do sistema e instale as dependências necessárias
RUN apt-get update && apt-get install -y \
    libgl1 \
    libsqlite3-dev \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

# Crie um ambiente Conda e instale o GDAL e SQLite com versões específicas
RUN conda create -n myenv python=3.10 --yes && \
    conda install -n myenv -c conda-forge gdal=3.4.1 sqlite=3.37.0 --yes

# Instale o restante dos pacotes usando pip
COPY requirements.txt . 
RUN conda run -n myenv pip install --no-cache-dir -r requirements.txt

# Verifique se GDAL está instalado corretamente
RUN conda run -n myenv python -c "from osgeo import gdal; print(gdal.__version__)"

# Copie o restante do código da aplicação para o contêiner
COPY . /app
WORKDIR /app

# Exponha a porta 3002
EXPOSE 3002

# Ative o ambiente Conda e execute o aplicativo
CMD ["conda", "run", "-n", "myenv", "python", "app.py"]